
try:
    print ''' 		       _           _    ______ _       _       
  	   _          | |         | |   | ___ \ |     | |      
  	  | \	  __ _| | __ _  __| |___| |_/ / |_   _| |_ ____
  	  |  \	 / _` | |/ _` |/ _` |_  / ___ \ | | | | __|_  /
  ()########  |=================================================>
  	  |  /	| (_| | | (_| | (_| |/ /| |_/ / | |_| | |_ / / 
  	  |_/	 \__, |_|\__,_|\__,_/___\____/|_|\__,_|\__/___|
  	     /    __/ |           ( Making Wordlist )    
  	    / \  |___/                                              
  	   /   \                                                
  	 _/     \_________________________________________________                                                  
	| gladzBlutz Coded By  : Teguh Sasongko ( ./Mr.GLADz404 ) |
	| Version              : 1.0                     	  | 	 
	| Codename             : gladzBlutz ( Making Wordlist )   | 
	| Follow me on FB      : www.fb.com/gladz404.id	 	  |   
	| My Blog	       : www.teguhsasongko.tk   	  | 	  
	| Greetz	       : IndoXploit & All My Friends  	  | 	  
	-----------------------------------------------------------	
'''
    print "\n"
    nama = raw_input("    Masukan Nama File Output : ")
    kata = open(nama,'a+')
    print "\n"
    print "    Masukan Kata yang ingin di buat :"
    a = raw_input('    Kata Pertama    : ')
    b = raw_input('    Kata Kedua      : ')
    c = raw_input('    Kata Ketiga     : ')
    d = raw_input('    Kata Keempat    : ')
    e = raw_input('    Kata Kelima     : ')
    f = raw_input('    Kata Keenam     : ')
    g = raw_input('    Kata Ketujuh    : ')
    h = raw_input('    Kata Kedelapan  : ')
    i = raw_input('    Kata Kesembilan : ')
    j = raw_input('    Kata Kesepuluh  : ')

    kata.write(a)
    kata.write('\n')
    kata.write(b)
    kata.write('\n')
    kata.write(c)
    kata.write('\n')
    kata.write(d)
    kata.write('\n')
    kata.write(e)
    kata.write('\n')
    kata.write(f)
    kata.write('\n')
    kata.write(g)
    kata.write('\n')
    kata.write(h)
    kata.write('\n')
    kata.write(i)
    kata.write('\n')
    kata.write(j)
    kata.write('\n')
    kata.write(a + b)
    kata.write('\n')
    kata.write(a + c)
    kata.write('\n')
    kata.write(a + d)
    kata.write('\n')
    kata.write(a + e)
    kata.write('\n')
    kata.write(a + f)
    kata.write('\n')
    kata.write(a + g)
    kata.write('\n')
    kata.write(a + h)
    kata.write('\n')
    kata.write(a + i)
    kata.write('\n')
    kata.write(a + j)
    kata.write('\n')
    kata.write(b + a)
    kata.write('\n')
    kata.write(b + c)
    kata.write('\n')
    kata.write(b + d)
    kata.write('\n')
    kata.write(b + e)
    kata.write('\n')
    kata.write(b + f)
    kata.write('\n')
    kata.write(b + g)
    kata.write('\n')
    kata.write(b + h)
    kata.write('\n')
    kata.write(b + i)
    kata.write('\n')
    kata.write(b + j)
    kata.write('\n')
    kata.write(c + a)
    kata.write('\n')
    kata.write(c + b)
    kata.write('\n')
    kata.write(c + d)
    kata.write('\n')
    kata.write(c + e)
    kata.write('\n')
    kata.write(c + f)
    kata.write('\n')
    kata.write(c + g)
    kata.write('\n')
    kata.write(c + h)
    kata.write('\n')
    kata.write(c + i)
    kata.write('\n')
    kata.write(c + j)
    kata.write('\n')
    kata.write(d + a)
    kata.write('\n')
    kata.write(d + b)
    kata.write('\n')
    kata.write(d + c)
    kata.write('\n')
    kata.write(d + e)
    kata.write('\n')
    kata.write(d + f)
    kata.write('\n')
    kata.write(d + g)
    kata.write('\n')
    kata.write(d + h)
    kata.write('\n')
    kata.write(d + i)
    kata.write('\n')
    kata.write(d + j)
    kata.write('\n')
    kata.write(e + a)
    kata.write('\n')
    kata.write(e + b)
    kata.write('\n')
    kata.write(e + c)
    kata.write('\n')
    kata.write(e + d)
    kata.write('\n')
    kata.write(e + f)
    kata.write('\n')
    kata.write(e + g)
    kata.write('\n')
    kata.write(e + h)
    kata.write('\n')
    kata.write(e + i)
    kata.write('\n')
    kata.write(e + j)
    kata.write('\n')
    kata.write(f + a)
    kata.write('\n')
    kata.write(f + b)
    kata.write('\n')
    kata.write(f + c)
    kata.write('\n')
    kata.write(f + d)
    kata.write('\n')
    kata.write(f + e)
    kata.write('\n')
    kata.write(f + g)
    kata.write('\n')
    kata.write(f + h)
    kata.write('\n')
    kata.write(f + i)
    kata.write('\n')
    kata.write(f + j)
    kata.write('\n')
    kata.write(g + a)
    kata.write('\n')
    kata.write(g + b)
    kata.write('\n')
    kata.write(g + c)
    kata.write('\n')
    kata.write(g + d)
    kata.write('\n')
    kata.write(g + e)
    kata.write('\n')
    kata.write(g + f)
    kata.write('\n')
    kata.write(g + h)
    kata.write('\n')
    kata.write(g + i)
    kata.write('\n')
    kata.write(g + j)
    kata.write('\n')
    kata.write(h + a)
    kata.write('\n')
    kata.write(h + b)
    kata.write('\n')
    kata.write(h + c)
    kata.write('\n')
    kata.write(h + d)
    kata.write('\n')
    kata.write(h + e)
    kata.write('\n')
    kata.write(h + f)
    kata.write('\n')
    kata.write(h + g)
    kata.write('\n')
    kata.write(h + i)
    kata.write('\n') 
    kata.write(h + j)
    kata.write('\n')
    kata.write(i + a)
    kata.write('\n')
    kata.write(i + b)
    kata.write('\n')
    kata.write(i + c)
    kata.write('\n')
    kata.write(i + d)
    kata.write('\n')
    kata.write(i + e)
    kata.write('\n')
    kata.write(i + f)
    kata.write('\n')
    kata.write(i + g)
    kata.write('\n')
    kata.write(i + h)
    kata.write('\n') 
    kata.write(i + j)
    kata.write('\n')
    kata.write(j + a)
    kata.write('\n')
    kata.write(j + b)
    kata.write('\n')
    kata.write(j + c)
    kata.write('\n')
    kata.write(j + d)
    kata.write('\n')
    kata.write(j + e)
    kata.write('\n')
    kata.write(j + f)
    kata.write('\n')
    kata.write(j + g)
    kata.write('\n')
    kata.write(j + h)
    kata.write('\n') 
    kata.write(j + i)
    kata.write('\n')  
    kata.write(a + b + c)
    kata.write('\n')
    kata.write(a + b + d)
    kata.write('\n')
    kata.write(a + b + e)
    kata.write('\n')
    kata.write(a + b + f)
    kata.write('\n')
    kata.write(a + b + g)
    kata.write('\n')
    kata.write(a + b + h)
    kata.write('\n')
    kata.write(a + b + i)
    kata.write('\n')
    kata.write(a + b + j)
    kata.write('\n')
    kata.write(a + c + b)
    kata.write('\n')
    kata.write(a + c + d)
    kata.write('\n')
    kata.write(a + c + e)
    kata.write('\n')
    kata.write(a + c + f)
    kata.write('\n')
    kata.write(a + c + g)
    kata.write('\n')
    kata.write(a + c + h)
    kata.write('\n')
    kata.write(a + c + i)
    kata.write('\n')
    kata.write(a + c + j)
    kata.write('\n')
    kata.write(a + d + b)
    kata.write('\n')
    kata.write(a + d + c)
    kata.write('\n')
    kata.write(a + d + e)
    kata.write('\n')
    kata.write(a + d + f)
    kata.write('\n')
    kata.write(a + d + g)
    kata.write('\n')
    kata.write(a + d + h)
    kata.write('\n')
    kata.write(a + d + i)
    kata.write('\n')
    kata.write(a + d + j)
    kata.write('\n')
    kata.write(a + e + b)
    kata.write('\n')
    kata.write(a + e + c)
    kata.write('\n')
    kata.write(a + e + d)
    kata.write('\n')
    kata.write(a + e + f)
    kata.write('\n')
    kata.write(a + e + g)
    kata.write('\n')
    kata.write(a + e + h)
    kata.write('\n')
    kata.write(a + e + i)
    kata.write('\n')
    kata.write(a + e + j)
    kata.write('\n')
    kata.write(a + f + b)
    kata.write('\n')
    kata.write(a + f + c)
    kata.write('\n')
    kata.write(a + f + d)
    kata.write('\n')
    kata.write(a + f + e)
    kata.write('\n')
    kata.write(a + f + g)
    kata.write('\n')
    kata.write(a + f + h)
    kata.write('\n')
    kata.write(a + f + i)
    kata.write('\n')
    kata.write(a + f + j)
    kata.write('\n')
    kata.write(a + g + b)
    kata.write('\n')
    kata.write(a + g + c)
    kata.write('\n')
    kata.write(a + g + d)
    kata.write('\n')
    kata.write(a + g + e)
    kata.write('\n')
    kata.write(a + g + f)
    kata.write('\n')
    kata.write(a + g + h)
    kata.write('\n')
    kata.write(a + g + i)
    kata.write('\n')
    kata.write(a + g + j)
    kata.write('\n')
    kata.write(a + h + b)
    kata.write('\n')
    kata.write(a + h + c)
    kata.write('\n')
    kata.write(a + h + d)
    kata.write('\n')
    kata.write(a + h + e)
    kata.write('\n')
    kata.write(a + h + f)
    kata.write('\n')
    kata.write(a + h + g)
    kata.write('\n')
    kata.write(a + h + i)
    kata.write('\n')
    kata.write(a + h + j)
    kata.write('\n')
    kata.write(a + i + b)
    kata.write('\n')
    kata.write(a + i + c)
    kata.write('\n')
    kata.write(a + i + d)
    kata.write('\n')
    kata.write(a + i + e)
    kata.write('\n')
    kata.write(a + i + f)
    kata.write('\n')
    kata.write(a + i + g)
    kata.write('\n')
    kata.write(a + i + h)
    kata.write('\n')
    kata.write(a + i + j)
    kata.write('\n')
    kata.write(a + j + b)
    kata.write('\n')
    kata.write(a + j + c)
    kata.write('\n')
    kata.write(a + j + d)
    kata.write('\n')
    kata.write(a + j + e)
    kata.write('\n')
    kata.write(a + j + f)
    kata.write('\n')
    kata.write(a + j + g)
    kata.write('\n')
    kata.write(a + j + h)
    kata.write('\n')
    kata.write(a + j + i)
    kata.write('\n')
    kata.write(b + a + c)
    kata.write('\n')
    kata.write(b + a + d)
    kata.write('\n')
    kata.write(b + a + e)
    kata.write('\n')
    kata.write(b + a + f)
    kata.write('\n')
    kata.write(b + a + g)
    kata.write('\n')
    kata.write(b + a + h)
    kata.write('\n')
    kata.write(b + a + i)
    kata.write('\n')
    kata.write(b + a + j)
    kata.write('\n')
    kata.write(b + c + a)
    kata.write('\n')
    kata.write(b + c + d)
    kata.write('\n')
    kata.write(b + c + e)
    kata.write('\n')
    kata.write(b + c + f)
    kata.write('\n')
    kata.write(b + c + g)
    kata.write('\n')
    kata.write(b + c + h)
    kata.write('\n')
    kata.write(b + c + i)
    kata.write('\n')
    kata.write(b + c + j)
    kata.write('\n')
    kata.write(b + d + a)
    kata.write('\n')
    kata.write(b + d + c)
    kata.write('\n')
    kata.write(b + d + e)
    kata.write('\n')
    kata.write(b + d + f)
    kata.write('\n')
    kata.write(b + d + g)
    kata.write('\n')
    kata.write(b + d + h)
    kata.write('\n')
    kata.write(b + d + i)
    kata.write('\n')
    kata.write(b + d + j)
    kata.write('\n')
    kata.write(b + e + a)
    kata.write('\n')
    kata.write(b + e + c)
    kata.write('\n')
    kata.write(b + e + d)
    kata.write('\n')
    kata.write(b + e + f)
    kata.write('\n')
    kata.write(b + e + g)
    kata.write('\n')
    kata.write(b + e + h)
    kata.write('\n')
    kata.write(b + e + i)
    kata.write('\n')
    kata.write(b + e + j)
    kata.write('\n')
    kata.write(b + f + a)
    kata.write('\n')
    kata.write(b + f + c)
    kata.write('\n')
    kata.write(b + f + d)
    kata.write('\n')
    kata.write(b + f + e)
    kata.write('\n')
    kata.write(b + f + g)
    kata.write('\n')
    kata.write(b + f + h)
    kata.write('\n')
    kata.write(b + f + i)
    kata.write('\n')
    kata.write(b + f + j)
    kata.write('\n')
    kata.write(b + g + a)
    kata.write('\n')
    kata.write(b + g + c)
    kata.write('\n')
    kata.write(b + g + d)
    kata.write('\n')
    kata.write(b + g + e)
    kata.write('\n')
    kata.write(b + g + f)
    kata.write('\n')
    kata.write(b + g + h)
    kata.write('\n')
    kata.write(b + g + i)
    kata.write('\n')
    kata.write(b + g + j)
    kata.write('\n')
    kata.write(b + h + a)
    kata.write('\n')
    kata.write(b + h + c)
    kata.write('\n')
    kata.write(b + h + d)
    kata.write('\n')
    kata.write(b + h + e)
    kata.write('\n')
    kata.write(b + h + f)
    kata.write('\n')
    kata.write(b + h + g)
    kata.write('\n')
    kata.write(b + h + i)
    kata.write('\n')
    kata.write(b + h + j)
    kata.write('\n')
    kata.write(b + i + a)
    kata.write('\n')
    kata.write(b + i + c)
    kata.write('\n')
    kata.write(b + i + d)
    kata.write('\n')
    kata.write(b + i + e)
    kata.write('\n')
    kata.write(b + i + f)
    kata.write('\n')
    kata.write(b + i + g)
    kata.write('\n')
    kata.write(b + i + h)
    kata.write('\n')
    kata.write(b + i + j)
    kata.write('\n')
    kata.write(b + j + a)
    kata.write('\n')
    kata.write(b + j + c)
    kata.write('\n')
    kata.write(b + j + d)
    kata.write('\n')
    kata.write(b + j + e)
    kata.write('\n')
    kata.write(b + j + f)
    kata.write('\n')
    kata.write(b + j + g)
    kata.write('\n')
    kata.write(b + j + h)
    kata.write('\n')
    kata.write(b + j + i)
    kata.write('\n')
    kata.write(c + a + b)
    kata.write('\n')
    kata.write(c + a + d)
    kata.write('\n')
    kata.write(c + a + e)
    kata.write('\n')
    kata.write(c + a + f)
    kata.write('\n')
    kata.write(c + a + g)
    kata.write('\n')
    kata.write(c + a + h)
    kata.write('\n')
    kata.write(c + a + i)
    kata.write('\n')
    kata.write(c + a + j)
    kata.write('\n')
    kata.write(c + b + a)
    kata.write('\n')
    kata.write(c + b + d)
    kata.write('\n')
    kata.write(c + b + e)
    kata.write('\n')
    kata.write(c + b + f)
    kata.write('\n')
    kata.write(c + b + g)
    kata.write('\n')
    kata.write(c + b + h)
    kata.write('\n')
    kata.write(c + b + i)
    kata.write('\n')
    kata.write(c + b + j)
    kata.write('\n')
    kata.write(c + d + a)
    kata.write('\n')
    kata.write(c + d + b)
    kata.write('\n')
    kata.write(c + d + e)
    kata.write('\n')
    kata.write(c + d + f)
    kata.write('\n')
    kata.write(c + d + g)
    kata.write('\n')
    kata.write(c + d + h)
    kata.write('\n')
    kata.write(c + d + i)
    kata.write('\n')
    kata.write(c + d + j)
    kata.write('\n')
    kata.write(c + e + a)
    kata.write('\n')
    kata.write(c + e + b)
    kata.write('\n')
    kata.write(c + e + d)
    kata.write('\n')
    kata.write(c + e + f)
    kata.write('\n')
    kata.write(c + e + g)
    kata.write('\n')
    kata.write(c + e + h)
    kata.write('\n')
    kata.write(c + e + i)
    kata.write('\n')
    kata.write(c + e + j)
    kata.write('\n')
    kata.write(d + a + b)
    kata.write('\n')
    kata.write(d + a + c)
    kata.write('\n')
    kata.write(d + a + e)
    kata.write('\n')
    kata.write(d + a + f)
    kata.write('\n')
    kata.write(d + a + g)
    kata.write('\n')
    kata.write(d + a + h)
    kata.write('\n')
    kata.write(d + a + i)
    kata.write('\n')
    kata.write(d + a + j)
    kata.write('\n')
    kata.write(d + b + a)
    kata.write('\n')
    kata.write(d + b + c)
    kata.write('\n')
    kata.write(d + b + e)
    kata.write('\n')
    kata.write(d + b + f)
    kata.write('\n')
    kata.write(d + b + g)
    kata.write('\n')
    kata.write(d + b + h)
    kata.write('\n')
    kata.write(d + b + i)
    kata.write('\n')
    kata.write(d + b + j)
    kata.write('\n')
    kata.write(d + c + a)
    kata.write('\n')
    kata.write(d + c + b)
    kata.write('\n')
    kata.write(d + c + e)
    kata.write('\n')
    kata.write(d + c + f)
    kata.write('\n')
    kata.write(d + c + g)
    kata.write('\n')
    kata.write(d + c + h)
    kata.write('\n')
    kata.write(d + c + i)
    kata.write('\n')
    kata.write(d + c + j)
    kata.write('\n')
    kata.write(d + e + a)
    kata.write('\n')
    kata.write(d + e + b)
    kata.write('\n')
    kata.write(d + e + c)
    kata.write('\n')
    kata.write(d + e + f)
    kata.write('\n')
    kata.write(d + e + g)
    kata.write('\n')
    kata.write(d + e + h)
    kata.write('\n')
    kata.write(d + e + i)
    kata.write('\n')
    kata.write(d + e + j)
    kata.write('\n')
    kata.write(d + f + a)
    kata.write('\n')
    kata.write(d + f + b)
    kata.write('\n')
    kata.write(d + f + c)
    kata.write('\n')
    kata.write(d + f + e)
    kata.write('\n')
    kata.write(d + f + g)
    kata.write('\n')
    kata.write(d + f + h)
    kata.write('\n')
    kata.write(d + f + i)
    kata.write('\n')
    kata.write(d + f + j)
    kata.write('\n')
    kata.write(d + g + a)
    kata.write('\n')
    kata.write(d + g + b)
    kata.write('\n')
    kata.write(d + g + c)
    kata.write('\n')
    kata.write(d + g + e)
    kata.write('\n')
    kata.write(d + g + f)
    kata.write('\n')
    kata.write(d + g + h)
    kata.write('\n')
    kata.write(d + g + i)
    kata.write('\n')
    kata.write(d + g + j)
    kata.write('\n')
    kata.write(d + h + a)
    kata.write('\n')
    kata.write(d + h + b)
    kata.write('\n')
    kata.write(d + h + c)
    kata.write('\n')
    kata.write(d + h + e)
    kata.write('\n')
    kata.write(d + h + f)
    kata.write('\n')
    kata.write(d + h + g)
    kata.write('\n')
    kata.write(d + h + i)
    kata.write('\n')
    kata.write(d + h + j)
    kata.write('\n')
    kata.write(d + i + a)
    kata.write('\n')
    kata.write(d + i + b)
    kata.write('\n')
    kata.write(d + i + c)
    kata.write('\n')
    kata.write(d + i + e)
    kata.write('\n')
    kata.write(d + i + f)
    kata.write('\n')
    kata.write(d + i + g)
    kata.write('\n')
    kata.write(d + i + h)
    kata.write('\n')
    kata.write(d + i + j)
    kata.write('\n')
    kata.write(d + j + a)
    kata.write('\n')
    kata.write(d + j + b)
    kata.write('\n')
    kata.write(d + j + c)
    kata.write('\n')
    kata.write(d + j + e)
    kata.write('\n')
    kata.write(d + j + f)
    kata.write('\n')
    kata.write(d + j + g)
    kata.write('\n')
    kata.write(d + j + h)
    kata.write('\n')
    kata.write(d + j + i)
    kata.write('\n')
    kata.write(e + a + b)
    kata.write('\n')
    kata.write(e + a + c)
    kata.write('\n')
    kata.write(e + a + d)
    kata.write('\n')
    kata.write(e + a + f)
    kata.write('\n')
    kata.write(e + a + g)
    kata.write('\n')
    kata.write(e + a + h)
    kata.write('\n')
    kata.write(e + a + i)
    kata.write('\n')
    kata.write(e + a + j)
    kata.write('\n')
    kata.write(e + b + a)
    kata.write('\n')
    kata.write(e + b + c)
    kata.write('\n')
    kata.write(e + b + d)
    kata.write('\n')
    kata.write(e + b + f)
    kata.write('\n')
    kata.write(e + b + g)
    kata.write('\n')
    kata.write(e + b + h)
    kata.write('\n')
    kata.write(e + b + i)
    kata.write('\n')
    kata.write(e + b + j)
    kata.write('\n')
    kata.write(e + c + a)
    kata.write('\n')
    kata.write(e + c + b)
    kata.write('\n')
    kata.write(e + c + d)
    kata.write('\n')
    kata.write(e + c + f)
    kata.write('\n')
    kata.write(e + c + g)
    kata.write('\n')
    kata.write(e + c + h)
    kata.write('\n')
    kata.write(e + c + i)
    kata.write('\n')
    kata.write(e + d + a)
    kata.write('\n')
    kata.write(e + d + b)
    kata.write('\n')
    kata.write(e + d + c)
    kata.write('\n')
    kata.write(e + d + f)
    kata.write('\n')
    kata.write(e + d + g)
    kata.write('\n')
    kata.write(e + d + h)
    kata.write('\n')
    kata.write(e + d + i)
    kata.write('\n')
    kata.write(e + d + j)
    kata.write('\n')
    kata.write(f + a + b)
    kata.write('\n')
    kata.write(f + a + c)
    kata.write('\n')
    kata.write(f + a + d)
    kata.write('\n')
    kata.write(f + a + e)
    kata.write('\n')
    kata.write(f + a + g)
    kata.write('\n')
    kata.write(f + a + h)
    kata.write('\n')
    kata.write(f + a + i)
    kata.write('\n')
    kata.write(f + a + j)
    kata.write('\n')
    kata.write(f + b + a)
    kata.write('\n')
    kata.write(f + b + c)
    kata.write('\n')
    kata.write(f + b + d)
    kata.write('\n')
    kata.write(f + b + e)
    kata.write('\n')
    kata.write(f + b + g)
    kata.write('\n')
    kata.write(f + b + h)
    kata.write('\n')
    kata.write(f + b + i)
    kata.write('\n')
    kata.write(f + b + j)
    kata.write('\n')
    kata.write(f + c + a)
    kata.write('\n')
    kata.write(f + c + b)
    kata.write('\n')
    kata.write(f + c + d)
    kata.write('\n')
    kata.write(f + c + e)
    kata.write('\n')
    kata.write(f + c + g)
    kata.write('\n')
    kata.write(f + c + h)
    kata.write('\n')
    kata.write(f + c + i)
    kata.write('\n')
    kata.write(f + c + j)
    kata.write('\n')
    kata.write(f + d + a)
    kata.write('\n')
    kata.write(f + d + b)
    kata.write('\n')
    kata.write(f + d + c)
    kata.write('\n')
    kata.write(f + d + e)
    kata.write('\n')
    kata.write(f + d + g)
    kata.write('\n')
    kata.write(f + d + h)
    kata.write('\n')
    kata.write(f + d + i)
    kata.write('\n')
    kata.write(f + d + j)
    kata.write('\n')
    kata.write(g + a + b)
    kata.write('\n')
    kata.write(g + a + c)
    kata.write('\n')
    kata.write(g + a + d)
    kata.write('\n')
    kata.write(g + a + e)
    kata.write('\n')
    kata.write(g + a + f)
    kata.write('\n')
    kata.write(g + a + h)
    kata.write('\n')
    kata.write(g + a + i)
    kata.write('\n')
    kata.write(g + a + j)
    kata.write('\n')
    kata.write(g + b + a)
    kata.write('\n')
    kata.write(g + b + c)
    kata.write('\n')
    kata.write(g + b + d)
    kata.write('\n')
    kata.write(g + b + e)
    kata.write('\n')
    kata.write(g + b + f)
    kata.write('\n')
    kata.write(g + b + h)
    kata.write('\n')
    kata.write(g + b + i)
    kata.write('\n')
    kata.write(g + b + j)
    kata.write('\n')
    kata.write(g + c + a)
    kata.write('\n')
    kata.write(g + c + b)
    kata.write('\n')
    kata.write(g + c + d)
    kata.write('\n')
    kata.write(g + c + e)
    kata.write('\n')
    kata.write(g + c + f)
    kata.write('\n')
    kata.write(g + c + h)
    kata.write('\n')
    kata.write(g + c + i)
    kata.write('\n')
    kata.write(g + c + j)
    kata.write('\n')
    kata.write(g + d + a)
    kata.write('\n')
    kata.write(g + d + b)
    kata.write('\n')
    kata.write(g + d + c)
    kata.write('\n')
    kata.write(g + d + e)
    kata.write('\n')
    kata.write(g + d + f)
    kata.write('\n')
    kata.write(g + d + h)
    kata.write('\n')
    kata.write(g + d + i)
    kata.write('\n')
    kata.write(g + d + j)
    kata.write('\n')
    kata.write(g + e + a)
    kata.write('\n')
    kata.write(g + e + b)
    kata.write('\n')
    kata.write(g + e + c)
    kata.write('\n')
    kata.write(g + e + d)
    kata.write('\n')
    kata.write(g + e + f)
    kata.write('\n')
    kata.write(g + e + h)
    kata.write('\n')
    kata.write(g + e + i)
    kata.write('\n')
    kata.write(g + e + j)
    kata.write('\n')
    kata.write(g + f + a)
    kata.write('\n')
    kata.write(g + f + b)
    kata.write('\n')
    kata.write(g + f + c)
    kata.write('\n')
    kata.write(g + f + d)
    kata.write('\n')
    kata.write(g + f + e)
    kata.write('\n')
    kata.write(g + f + h)
    kata.write('\n')
    kata.write(g + f + i)
    kata.write('\n')
    kata.write(g + f + j)
    kata.write('\n')
    kata.write(g + e + a)
    kata.write('\n')
    kata.write(g + e + b)
    kata.write('\n')
    kata.write(g + e + c)
    kata.write('\n')
    kata.write(g + e + d)
    kata.write('\n')
    kata.write(g + e + f)
    kata.write('\n')
    kata.write(g + e + h)
    kata.write('\n')
    kata.write(g + e + i)
    kata.write('\n')
    kata.write(g + e + j)
    kata.write('\n')
    kata.write(g + h + a)
    kata.write('\n')
    kata.write(g + h + b)
    kata.write('\n')
    kata.write(g + h + c)
    kata.write('\n')
    kata.write(g + h + d)
    kata.write('\n')
    kata.write(g + h + f)
    kata.write('\n')
    kata.write(g + h + e)
    kata.write('\n')
    kata.write(g + h + i)
    kata.write('\n')
    kata.write(g + h + j)
    kata.write('\n')
    kata.write(g + i + a)
    kata.write('\n')
    kata.write(g + i + b)
    kata.write('\n')
    kata.write(g + i + c)
    kata.write('\n')
    kata.write(g + i + d)
    kata.write('\n')
    kata.write(g + i + f)
    kata.write('\n')
    kata.write(g + i + e)
    kata.write('\n')
    kata.write(g + i + h)
    kata.write('\n')
    kata.write(g + i + j)
    kata.write('\n')
    kata.write(g + j + a)
    kata.write('\n')
    kata.write(g + j + b)
    kata.write('\n')
    kata.write(g + j + c)
    kata.write('\n')
    kata.write(g + j + d)
    kata.write('\n')
    kata.write(g + j + f)
    kata.write('\n')
    kata.write(g + j + e)
    kata.write('\n')
    kata.write(g + j + h)
    kata.write('\n')
    kata.write(g + j + i)
    kata.write('\n')
    kata.write(h + a + b)
    kata.write('\n')
    kata.write(h + a + c)
    kata.write('\n')
    kata.write(h + a + d)
    kata.write('\n')
    kata.write(h + a + e)
    kata.write('\n')
    kata.write(h + a + f)
    kata.write('\n')
    kata.write(h + a + g)
    kata.write('\n')
    kata.write(h + a + i)
    kata.write('\n')
    kata.write(h + a + j)
    kata.write('\n')
    kata.write(h + b + a)
    kata.write('\n')
    kata.write(h + b + c)
    kata.write('\n')
    kata.write(h + b + d)
    kata.write('\n')
    kata.write(h + b + e)
    kata.write('\n')
    kata.write(h + b + f)
    kata.write('\n')
    kata.write(h + b + g)
    kata.write('\n')
    kata.write(h + b + i)
    kata.write('\n')
    kata.write(h + b + j)
    kata.write('\n')
    kata.write(h + c + a)
    kata.write('\n')
    kata.write(h + c + b)
    kata.write('\n')
    kata.write(h + c + d)
    kata.write('\n')
    kata.write(h + c + e)
    kata.write('\n')
    kata.write(h + c + f)
    kata.write('\n')
    kata.write(h + c + g)
    kata.write('\n')
    kata.write(h + c + i)
    kata.write('\n')
    kata.write(h + c + j)
    kata.write('\n')
    kata.write(h + d + a)
    kata.write('\n')
    kata.write(h + d + b)
    kata.write('\n')
    kata.write(h + d + c)
    kata.write('\n')
    kata.write(h + d + e)
    kata.write('\n')
    kata.write(h + d + f)
    kata.write('\n')
    kata.write(h + d + g)
    kata.write('\n')
    kata.write(h + d + i)
    kata.write('\n')
    kata.write(h + d + j)
    kata.write('\n')
    kata.write(h + e + a)
    kata.write('\n')
    kata.write(h + e + b)
    kata.write('\n')
    kata.write(h + e + c)
    kata.write('\n')
    kata.write(h + e + d)
    kata.write('\n')
    kata.write(h + e + f)
    kata.write('\n')
    kata.write(h + e + g)
    kata.write('\n')
    kata.write(h + e + i)
    kata.write('\n')
    kata.write(h + e + j)
    kata.write('\n')
    kata.write(h + f + a)
    kata.write('\n')
    kata.write(h + f + b)
    kata.write('\n')
    kata.write(h + f + c)
    kata.write('\n')
    kata.write(h + f + d)
    kata.write('\n')
    kata.write(h + f + e)
    kata.write('\n')
    kata.write(h + f + g)
    kata.write('\n')
    kata.write(h + f + i)
    kata.write('\n')
    kata.write(h + f + j)
    kata.write('\n')
    kata.write(h + g + a)
    kata.write('\n')
    kata.write(h + g + b)
    kata.write('\n')
    kata.write(h + g + c)
    kata.write('\n')
    kata.write(h + g + d)
    kata.write('\n')
    kata.write(h + g + e)
    kata.write('\n')
    kata.write(h + g + f)
    kata.write('\n')
    kata.write(h + g + i)
    kata.write('\n')
    kata.write(h + g + j) 
    kata.write('\n')
    kata.write(h + i + a)
    kata.write('\n')
    kata.write(h + i + b)
    kata.write('\n')
    kata.write(h + i + c)
    kata.write('\n')
    kata.write(h + i + d)
    kata.write('\n')
    kata.write(h + i + e)
    kata.write('\n')
    kata.write(h + i + f)
    kata.write('\n')
    kata.write(h + i + g)
    kata.write('\n')
    kata.write(h + i + j)
    kata.write('\n')
    kata.write(h + j + a)
    kata.write('\n')
    kata.write(h + j + b)
    kata.write('\n')
    kata.write(h + j + c)
    kata.write('\n')
    kata.write(h + j + d)
    kata.write('\n')
    kata.write(h + j + e)
    kata.write('\n')
    kata.write(h + j + f)
    kata.write('\n')
    kata.write(h + j + g)
    kata.write('\n')
    kata.write(h + j + i)
    kata.write('\n')
    kata.write(i + a + c)
    kata.write('\n')
    kata.write(i + a + d)
    kata.write('\n')
    kata.write(i + a + e)
    kata.write('\n')
    kata.write(i + a + f)
    kata.write('\n')
    kata.write(i + a + g)
    kata.write('\n')
    kata.write(i + a + h)
    kata.write('\n')
    kata.write(i + a + j)
    kata.write('\n')
    kata.write(i + b + a)
    kata.write('\n')
    kata.write(i + b + c)
    kata.write('\n')
    kata.write(i + b + d)
    kata.write('\n')
    kata.write(i + b + e)
    kata.write('\n')
    kata.write(i + b + f)
    kata.write('\n')
    kata.write(i + b + g)
    kata.write('\n')
    kata.write(i + b + h)
    kata.write('\n')
    kata.write(i + b + j)
    kata.write('\n')
    kata.write(i + c + a)
    kata.write('\n')
    kata.write(i + c + b)
    kata.write('\n')
    kata.write(i + c + d)
    kata.write('\n')
    kata.write(i + c + e)
    kata.write('\n')
    kata.write(i + c + f)
    kata.write('\n')
    kata.write(i + c + g)
    kata.write('\n')
    kata.write(i + c + h)
    kata.write('\n')
    kata.write(i + c + j)
    kata.write('\n')
    kata.write(i + d + a)
    kata.write('\n')
    kata.write(i + d + b)
    kata.write('\n')
    kata.write(i + d + c)
    kata.write('\n')
    kata.write(i + d + e)
    kata.write('\n')
    kata.write(i + d + f)
    kata.write('\n')
    kata.write(i + d + g)
    kata.write('\n')
    kata.write(i + d + h)
    kata.write('\n')
    kata.write(i + d + j)
    kata.write('\n')
    kata.write(i + e + a)
    kata.write('\n')
    kata.write(i + e + b)
    kata.write('\n')
    kata.write(i + e + c)
    kata.write('\n')
    kata.write(i + e + d)
    kata.write('\n')
    kata.write(i + e + f)
    kata.write('\n')
    kata.write(i + e + g)
    kata.write('\n')
    kata.write(i + e + h)
    kata.write('\n')
    kata.write(i + e + j)
    kata.write('\n')
    kata.write(i + f + a)
    kata.write('\n')
    kata.write(i + f + b)
    kata.write('\n')
    kata.write(i + f + c)
    kata.write('\n')
    kata.write(i + f + d)
    kata.write('\n')
    kata.write(i + f + e)
    kata.write('\n')
    kata.write(i + f + g)
    kata.write('\n')
    kata.write(i + f + h)
    kata.write('\n')
    kata.write(i + f + j)
    kata.write('\n')
    kata.write(i + g + a)
    kata.write('\n')
    kata.write(i + g + b)
    kata.write('\n')
    kata.write(i + g + c)
    kata.write('\n')
    kata.write(i + g + d)
    kata.write('\n')
    kata.write(i + g + e)
    kata.write('\n')
    kata.write(i + g + f)
    kata.write('\n')
    kata.write(i + g + h)
    kata.write('\n')
    kata.write(i + g + j) 
    kata.write('\n')
    kata.write(i + h + a)
    kata.write('\n')
    kata.write(i + h + b)
    kata.write('\n')
    kata.write(i + h + c)
    kata.write('\n')
    kata.write(i + h + d)
    kata.write('\n')
    kata.write(i + h + e)
    kata.write('\n')
    kata.write(i + h + f)
    kata.write('\n')
    kata.write(i + h + g)
    kata.write('\n')
    kata.write(i + h + j)
    kata.write('\n')
    kata.write(i + j + a)
    kata.write('\n')
    kata.write(i + j + b)
    kata.write('\n')
    kata.write(i + j + c)
    kata.write('\n')
    kata.write(i + j + d)
    kata.write('\n')
    kata.write(i + j + e)
    kata.write('\n')
    kata.write(i + j + f)
    kata.write('\n')
    kata.write(i + j + g)
    kata.write('\n')
    kata.write(i + j + h)
    kata.write('\n')
    kata.write(j + a + c)
    kata.write('\n')
    kata.write(j + a + d)
    kata.write('\n')
    kata.write(j + a + e)
    kata.write('\n')
    kata.write(j + a + f)
    kata.write('\n')
    kata.write(j + a + g)
    kata.write('\n')
    kata.write(j + a + h)
    kata.write('\n')
    kata.write(j + a + i)
    kata.write('\n')
    kata.write(j + b + a)
    kata.write('\n')
    kata.write(j + b + c)
    kata.write('\n')
    kata.write(j + b + d)
    kata.write('\n')
    kata.write(j + b + e)
    kata.write('\n')
    kata.write(j + b + f)
    kata.write('\n')
    kata.write(j + b + g)
    kata.write('\n')
    kata.write(j + b + h)
    kata.write('\n')
    kata.write(j + b + i)
    kata.write('\n')
    kata.write(j + c + a)
    kata.write('\n')
    kata.write(j + c + b)
    kata.write('\n')
    kata.write(j + c + d)
    kata.write('\n')
    kata.write(j + c + e)
    kata.write('\n')
    kata.write(j + c + f)
    kata.write('\n')
    kata.write(j + c + g)
    kata.write('\n')
    kata.write(j + c + h)
    kata.write('\n')
    kata.write(j + c + i)
    kata.write('\n')
    kata.write(j + d + a)
    kata.write('\n')
    kata.write(j + d + b)
    kata.write('\n')
    kata.write(j + d + c)
    kata.write('\n')
    kata.write(j + d + e)
    kata.write('\n')
    kata.write(j + d + f)
    kata.write('\n')
    kata.write(j + d + g)
    kata.write('\n')
    kata.write(j + d + h)
    kata.write('\n')
    kata.write(j + d + i)
    kata.write('\n')
    kata.write(j + e + a)
    kata.write('\n')
    kata.write(j + e + b)
    kata.write('\n')
    kata.write(j + e + c)
    kata.write('\n')
    kata.write(j + e + d)
    kata.write('\n')
    kata.write(j + e + f)
    kata.write('\n')
    kata.write(j + e + g)
    kata.write('\n')
    kata.write(j + e + h)
    kata.write('\n')
    kata.write(j + e + i)
    kata.write('\n')
    kata.write(j + f + a)
    kata.write('\n')
    kata.write(j + f + b)
    kata.write('\n')
    kata.write(j + f + c)
    kata.write('\n')
    kata.write(j + f + d)
    kata.write('\n')
    kata.write(j + f + e)
    kata.write('\n')
    kata.write(j + f + g)
    kata.write('\n')
    kata.write(j + f + h)
    kata.write('\n')
    kata.write(j + f + i)
    kata.write('\n')
    kata.write(j + g + a)
    kata.write('\n')
    kata.write(j + g + b)
    kata.write('\n')
    kata.write(j + g + c)
    kata.write('\n')
    kata.write(j + g + d)
    kata.write('\n')
    kata.write(j + g + e)
    kata.write('\n')
    kata.write(j + g + f)
    kata.write('\n')
    kata.write(j + g + h)
    kata.write('\n')
    kata.write(j + g + i) 
    kata.write('\n')
    kata.write(j + h + a)
    kata.write('\n')
    kata.write(j + h + b)
    kata.write('\n')
    kata.write(j + h + c)
    kata.write('\n')
    kata.write(j + h + d)
    kata.write('\n')
    kata.write(j + h + e)
    kata.write('\n')
    kata.write(j + h + f)
    kata.write('\n')
    kata.write(j + h + g)
    kata.write('\n')
    kata.write(j + h + i)
    kata.write('\n')
    kata.write(j + i + a)
    kata.write('\n')
    kata.write(j + i + b)
    kata.write('\n')
    kata.write(j + i + c)
    kata.write('\n')
    kata.write(j + i + d)
    kata.write('\n')
    kata.write(j + i + e)
    kata.write('\n')
    kata.write(j + i + f)
    kata.write('\n')
    kata.write(j + i + g)
    kata.write('\n')
    kata.write(j + i + h)
    print '''
     _  _  _  _       _  _  _  _    _           _  _  _  _  _     
    (_)(_)(_)(_)    _(_)(_)(_)(_)_ (_) _       (_)(_)(_)(_)(_) 
    (_)       (_)_ (_)          (_)(_)(_)_     (_)(_)               
    (_)         (_)(_)          (_)(_)  (_)_   (_)(_) _  _          
    (_)         (_)(_)          (_)(_)    (_)_ (_)(_)(_)(_)         
    (_)        _(_)(_)          (_)(_)      (_)(_)(_)               
    (_) _  _  (_)  (_)_  _  _  _(_)(_)         (_)(_) _  _  _     
    (_)(_)(_)(_)    (_)(_)(_)(_)   (_)         (_)(_)(_)(_)(_)   
    File disimpan sebagai ''' + nama
except KeyboardInterrupt:
    print '''
    |----------------------------------|
    | Anda Telah Membatalkan  !!	   |
    |----------------------------------|
    '''
