#!/usr/bin/python
# Author : Teguh Sasongko ( ./Mr.GLADz404 )
# FREE RECODED ASAL SOPAN !!!
try:
    print '''\033[1;91m 		       _           _    ______ _       _ \033[1;m      
 \033[1;36m 	   _ \033[1;m    \033[1;91m     | |         | |   | ___ \ |     | |          \033[1;m
 \033[1;36m 	  | \ \033[1;m	  \033[1;91m__ _| | __ _  __| |___| |_/ / |_   _| |_ ____    \033[1;m
 \033[1;36m 	  |  \ \033[1;m	 \033[1;91m/ _` | |/ _` |/ _` |_  / ___ \ | | | | __|_  /    \033[1;m
 \033[1;36m ()########  |=================================================>\033[1;m
 \033[1;36m 	  |  /\033[1;m	\033[1;39m| (_| | | (_| | (_| |/ /| |_/ / | |_| | |_ / /_ \033[1;m
 \033[1;36m 	  |_/\033[1;m	 \033[1;39m\__, |_|\__,_|\__,_/___\____/|_|\__,_|\__/___| \033[1;m
\033[1;32m  	     /  \033[1;m \033[1;39m __/ | \033[1;m     \033[1;27m     ( Making Wordlist )   \033[1;m 
\033[1;32m  	    / \ \033[1;m \033[1;39m|___/ \033[1;m                                             
\033[1;32m  	   /   \  \033[1;m                                              
 \033[1;32m 	 _/     \_________________________________________________                                                  
	| gladzBlutz Coded By  : Teguh Sasongko ( ./Mr.GLADz404 ) |
	| Version              : 1.0                     	  | 	 
	| Codename             : gladzBlutz          		  | 
	| Follow me on FB      : www.fb.com/gladz404.id	 	  |   
	| My Blog	       : www.teguhsasongko.tk   	  | 	  
	| Greetz	       : IndoXploit & All My Friends  	  | 	  
	-----------------------------------------------------------\033[1;m	
'''
    print "\n"
    nama = raw_input("\033[1;17m    Masukan Nama File Output : \033[1;m")
    kataku = open (nama,'a+') 
    print "\n"
    print "\033[1;25m    Masukan kata yang ingin di buat : \033[1;m"
    a = raw_input('\033[1;25m    kata Pertama    : \033[1;m')
    b = raw_input('\033[1;17m    kata Kedua      : \033[1;m')
    c = raw_input('\033[1;17m    kata Ketiga     : \033[1;m')
    d = raw_input('\033[1;17m    kata Keempat    : \033[1;m')
    e = raw_input('\033[1;17m    kata Kelima     : \033[1;m')
    f = raw_input('\033[1;17m    kata Keenam     : \033[1;m')
    g = raw_input('\033[1;17m    kata Ketujuh    : \033[1;m')
    h = raw_input('\033[1;17m    kata Kedelapan  : \033[1;m')
    i = raw_input('\033[1;17m    kata Kesembilan : \033[1;m')
    j = raw_input('\033[1;17m    kata Kesepuluh  : \033[1;m')

    kataku.write(a)
    kataku.write('\n')
    kataku.write(b)
    kataku.write('\n')
    kataku.write(c)
    kataku.write('\n')
    kataku.write(d)
    kataku.write('\n')
    kataku.write(e)
    kataku.write('\n')
    kataku.write(f)
    kataku.write('\n')
    kataku.write(g)
    kataku.write('\n')
    kataku.write(h)
    kataku.write('\n')
    kataku.write(i)
    kataku.write('\n')
    kataku.write(j)
    kataku.write('\n')
    kataku.write(a + b)
    kataku.write('\n')
    kataku.write(a + c)
    kataku.write('\n')
    kataku.write(a + d)
    kataku.write('\n')
    kataku.write(a + e)
    kataku.write('\n')
    kataku.write(a + f)
    kataku.write('\n')
    kataku.write(a + g)
    kataku.write('\n')
    kataku.write(a + h)
    kataku.write('\n')
    kataku.write(a + i)
    kataku.write('\n')
    kataku.write(a + j)
    kataku.write('\n')
    kataku.write(b + a)
    kataku.write('\n')
    kataku.write(b + c)
    kataku.write('\n')
    kataku.write(b + d)
    kataku.write('\n')
    kataku.write(b + e)
    kataku.write('\n')
    kataku.write(b + f)
    kataku.write('\n')
    kataku.write(b + g)
    kataku.write('\n')
    kataku.write(b + h)
    kataku.write('\n')
    kataku.write(b + i)
    kataku.write('\n')
    kataku.write(b + j)
    kataku.write('\n')
    kataku.write(c + a)
    kataku.write('\n')
    kataku.write(c + b)
    kataku.write('\n')
    kataku.write(c + d)
    kataku.write('\n')
    kataku.write(c + e)
    kataku.write('\n')
    kataku.write(c + f)
    kataku.write('\n')
    kataku.write(c + g)
    kataku.write('\n')
    kataku.write(c + h)
    kataku.write('\n')
    kataku.write(c + i)
    kataku.write('\n')
    kataku.write(c + j)
    kataku.write('\n')
    kataku.write(d + a)
    kataku.write('\n')
    kataku.write(d + b)
    kataku.write('\n')
    kataku.write(d + c)
    kataku.write('\n')
    kataku.write(d + e)
    kataku.write('\n')
    kataku.write(d + f)
    kataku.write('\n')
    kataku.write(d + g)
    kataku.write('\n')
    kataku.write(d + h)
    kataku.write('\n')
    kataku.write(d + i)
    kataku.write('\n')
    kataku.write(d + j)
    kataku.write('\n')
    kataku.write(e + a)
    kataku.write('\n')
    kataku.write(e + b)
    kataku.write('\n')
    kataku.write(e + c)
    kataku.write('\n')
    kataku.write(e + d)
    kataku.write('\n')
    kataku.write(e + f)
    kataku.write('\n')
    kataku.write(e + g)
    kataku.write('\n')
    kataku.write(e + h)
    kataku.write('\n')
    kataku.write(e + i)
    kataku.write('\n')
    kataku.write(e + j)
    kataku.write('\n')
    kataku.write(f + a)
    kataku.write('\n')
    kataku.write(f + b)
    kataku.write('\n')
    kataku.write(f + c)
    kataku.write('\n')
    kataku.write(f + d)
    kataku.write('\n')
    kataku.write(f + e)
    kataku.write('\n')
    kataku.write(f + g)
    kataku.write('\n')
    kataku.write(f + h)
    kataku.write('\n')
    kataku.write(f + i)
    kataku.write('\n')
    kataku.write(f + j)
    kataku.write('\n')
    kataku.write(g + a)
    kataku.write('\n')
    kataku.write(g + b)
    kataku.write('\n')
    kataku.write(g + c)
    kataku.write('\n')
    kataku.write(g + d)
    kataku.write('\n')
    kataku.write(g + e)
    kataku.write('\n')
    kataku.write(g + f)
    kataku.write('\n')
    kataku.write(g + h)
    kataku.write('\n')
    kataku.write(g + i)
    kataku.write('\n')
    kataku.write(g + j)
    kataku.write('\n')
    kataku.write(h + a)
    kataku.write('\n')
    kataku.write(h + b)
    kataku.write('\n')
    kataku.write(h + c)
    kataku.write('\n')
    kataku.write(h + d)
    kataku.write('\n')
    kataku.write(h + e)
    kataku.write('\n')
    kataku.write(h + f)
    kataku.write('\n')
    kataku.write(h + g)
    kataku.write('\n')
    kataku.write(h + i)
    kataku.write('\n') 
    kataku.write(h + j)
    kataku.write('\n')
    kataku.write(i + a)
    kataku.write('\n')
    kataku.write(i + b)
    kataku.write('\n')
    kataku.write(i + c)
    kataku.write('\n')
    kataku.write(i + d)
    kataku.write('\n')
    kataku.write(i + e)
    kataku.write('\n')
    kataku.write(i + f)
    kataku.write('\n')
    kataku.write(i + g)
    kataku.write('\n')
    kataku.write(i + h)
    kataku.write('\n') 
    kataku.write(i + j)
    kataku.write('\n')
    kataku.write(j + a)
    kataku.write('\n')
    kataku.write(j + b)
    kataku.write('\n')
    kataku.write(j + c)
    kataku.write('\n')
    kataku.write(j + d)
    kataku.write('\n')
    kataku.write(j + e)
    kataku.write('\n')
    kataku.write(j + f)
    kataku.write('\n')
    kataku.write(j + g)
    kataku.write('\n')
    kataku.write(j + h)
    kataku.write('\n') 
    kataku.write(j + i)
    kataku.write('\n')  
    kataku.write(a + b + c)
    kataku.write('\n')
    kataku.write(a + b + d)
    kataku.write('\n')
    kataku.write(a + b + e)
    kataku.write('\n')
    kataku.write(a + b + f)
    kataku.write('\n')
    kataku.write(a + b + g)
    kataku.write('\n')
    kataku.write(a + b + h)
    kataku.write('\n')
    kataku.write(a + b + i)
    kataku.write('\n')
    kataku.write(a + b + j)
    kataku.write('\n')
    kataku.write(a + c + b)
    kataku.write('\n')
    kataku.write(a + c + d)
    kataku.write('\n')
    kataku.write(a + c + e)
    kataku.write('\n')
    kataku.write(a + c + f)
    kataku.write('\n')
    kataku.write(a + c + g)
    kataku.write('\n')
    kataku.write(a + c + h)
    kataku.write('\n')
    kataku.write(a + c + i)
    kataku.write('\n')
    kataku.write(a + c + j)
    kataku.write('\n')
    kataku.write(a + d + b)
    kataku.write('\n')
    kataku.write(a + d + c)
    kataku.write('\n')
    kataku.write(a + d + e)
    kataku.write('\n')
    kataku.write(a + d + f)
    kataku.write('\n')
    kataku.write(a + d + g)
    kataku.write('\n')
    kataku.write(a + d + h)
    kataku.write('\n')
    kataku.write(a + d + i)
    kataku.write('\n')
    kataku.write(a + d + j)
    kataku.write('\n')
    kataku.write(a + e + b)
    kataku.write('\n')
    kataku.write(a + e + c)
    kataku.write('\n')
    kataku.write(a + e + d)
    kataku.write('\n')
    kataku.write(a + e + f)
    kataku.write('\n')
    kataku.write(a + e + g)
    kataku.write('\n')
    kataku.write(a + e + h)
    kataku.write('\n')
    kataku.write(a + e + i)
    kataku.write('\n')
    kataku.write(a + e + j)
    kataku.write('\n')
    kataku.write(a + f + b)
    kataku.write('\n')
    kataku.write(a + f + c)
    kataku.write('\n')
    kataku.write(a + f + d)
    kataku.write('\n')
    kataku.write(a + f + e)
    kataku.write('\n')
    kataku.write(a + f + g)
    kataku.write('\n')
    kataku.write(a + f + h)
    kataku.write('\n')
    kataku.write(a + f + i)
    kataku.write('\n')
    kataku.write(a + f + j)
    kataku.write('\n')
    kataku.write(a + g + b)
    kataku.write('\n')
    kataku.write(a + g + c)
    kataku.write('\n')
    kataku.write(a + g + d)
    kataku.write('\n')
    kataku.write(a + g + e)
    kataku.write('\n')
    kataku.write(a + g + f)
    kataku.write('\n')
    kataku.write(a + g + h)
    kataku.write('\n')
    kataku.write(a + g + i)
    kataku.write('\n')
    kataku.write(a + g + j)
    kataku.write('\n')
    kataku.write(a + h + b)
    kataku.write('\n')
    kataku.write(a + h + c)
    kataku.write('\n')
    kataku.write(a + h + d)
    kataku.write('\n')
    kataku.write(a + h + e)
    kataku.write('\n')
    kataku.write(a + h + f)
    kataku.write('\n')
    kataku.write(a + h + g)
    kataku.write('\n')
    kataku.write(a + h + i)
    kataku.write('\n')
    kataku.write(a + h + j)
    kataku.write('\n')
    kataku.write(a + i + b)
    kataku.write('\n')
    kataku.write(a + i + c)
    kataku.write('\n')
    kataku.write(a + i + d)
    kataku.write('\n')
    kataku.write(a + i + e)
    kataku.write('\n')
    kataku.write(a + i + f)
    kataku.write('\n')
    kataku.write(a + i + g)
    kataku.write('\n')
    kataku.write(a + i + h)
    kataku.write('\n')
    kataku.write(a + i + j)
    kataku.write('\n')
    kataku.write(a + j + b)
    kataku.write('\n')
    kataku.write(a + j + c)
    kataku.write('\n')
    kataku.write(a + j + d)
    kataku.write('\n')
    kataku.write(a + j + e)
    kataku.write('\n')
    kataku.write(a + j + f)
    kataku.write('\n')
    kataku.write(a + j + g)
    kataku.write('\n')
    kataku.write(a + j + h)
    kataku.write('\n')
    kataku.write(a + j + i)
    kataku.write('\n')
    kataku.write(b + a + c)
    kataku.write('\n')
    kataku.write(b + a + d)
    kataku.write('\n')
    kataku.write(b + a + e)
    kataku.write('\n')
    kataku.write(b + a + f)
    kataku.write('\n')
    kataku.write(b + a + g)
    kataku.write('\n')
    kataku.write(b + a + h)
    kataku.write('\n')
    kataku.write(b + a + i)
    kataku.write('\n')
    kataku.write(b + a + j)
    kataku.write('\n')
    kataku.write(b + c + a)
    kataku.write('\n')
    kataku.write(b + c + d)
    kataku.write('\n')
    kataku.write(b + c + e)
    kataku.write('\n')
    kataku.write(b + c + f)
    kataku.write('\n')
    kataku.write(b + c + g)
    kataku.write('\n')
    kataku.write(b + c + h)
    kataku.write('\n')
    kataku.write(b + c + i)
    kataku.write('\n')
    kataku.write(b + c + j)
    kataku.write('\n')
    kataku.write(b + d + a)
    kataku.write('\n')
    kataku.write(b + d + c)
    kataku.write('\n')
    kataku.write(b + d + e)
    kataku.write('\n')
    kataku.write(b + d + f)
    kataku.write('\n')
    kataku.write(b + d + g)
    kataku.write('\n')
    kataku.write(b + d + h)
    kataku.write('\n')
    kataku.write(b + d + i)
    kataku.write('\n')
    kataku.write(b + d + j)
    kataku.write('\n')
    kataku.write(b + e + a)
    kataku.write('\n')
    kataku.write(b + e + c)
    kataku.write('\n')
    kataku.write(b + e + d)
    kataku.write('\n')
    kataku.write(b + e + f)
    kataku.write('\n')
    kataku.write(b + e + g)
    kataku.write('\n')
    kataku.write(b + e + h)
    kataku.write('\n')
    kataku.write(b + e + i)
    kataku.write('\n')
    kataku.write(b + e + j)
    kataku.write('\n')
    kataku.write(b + f + a)
    kataku.write('\n')
    kataku.write(b + f + c)
    kataku.write('\n')
    kataku.write(b + f + d)
    kataku.write('\n')
    kataku.write(b + f + e)
    kataku.write('\n')
    kataku.write(b + f + g)
    kataku.write('\n')
    kataku.write(b + f + h)
    kataku.write('\n')
    kataku.write(b + f + i)
    kataku.write('\n')
    kataku.write(b + f + j)
    kataku.write('\n')
    kataku.write(b + g + a)
    kataku.write('\n')
    kataku.write(b + g + c)
    kataku.write('\n')
    kataku.write(b + g + d)
    kataku.write('\n')
    kataku.write(b + g + e)
    kataku.write('\n')
    kataku.write(b + g + f)
    kataku.write('\n')
    kataku.write(b + g + h)
    kataku.write('\n')
    kataku.write(b + g + i)
    kataku.write('\n')
    kataku.write(b + g + j)
    kataku.write('\n')
    kataku.write(b + h + a)
    kataku.write('\n')
    kataku.write(b + h + c)
    kataku.write('\n')
    kataku.write(b + h + d)
    kataku.write('\n')
    kataku.write(b + h + e)
    kataku.write('\n')
    kataku.write(b + h + f)
    kataku.write('\n')
    kataku.write(b + h + g)
    kataku.write('\n')
    kataku.write(b + h + i)
    kataku.write('\n')
    kataku.write(b + h + j)
    kataku.write('\n')
    kataku.write(b + i + a)
    kataku.write('\n')
    kataku.write(b + i + c)
    kataku.write('\n')
    kataku.write(b + i + d)
    kataku.write('\n')
    kataku.write(b + i + e)
    kataku.write('\n')
    kataku.write(b + i + f)
    kataku.write('\n')
    kataku.write(b + i + g)
    kataku.write('\n')
    kataku.write(b + i + h)
    kataku.write('\n')
    kataku.write(b + i + j)
    kataku.write('\n')
    kataku.write(b + j + a)
    kataku.write('\n')
    kataku.write(b + j + c)
    kataku.write('\n')
    kataku.write(b + j + d)
    kataku.write('\n')
    kataku.write(b + j + e)
    kataku.write('\n')
    kataku.write(b + j + f)
    kataku.write('\n')
    kataku.write(b + j + g)
    kataku.write('\n')
    kataku.write(b + j + h)
    kataku.write('\n')
    kataku.write(b + j + i)
    kataku.write('\n')
    kataku.write(c + a + b)
    kataku.write('\n')
    kataku.write(c + a + d)
    kataku.write('\n')
    kataku.write(c + a + e)
    kataku.write('\n')
    kataku.write(c + a + f)
    kataku.write('\n')
    kataku.write(c + a + g)
    kataku.write('\n')
    kataku.write(c + a + h)
    kataku.write('\n')
    kataku.write(c + a + i)
    kataku.write('\n')
    kataku.write(c + a + j)
    kataku.write('\n')
    kataku.write(c + b + a)
    kataku.write('\n')
    kataku.write(c + b + d)
    kataku.write('\n')
    kataku.write(c + b + e)
    kataku.write('\n')
    kataku.write(c + b + f)
    kataku.write('\n')
    kataku.write(c + b + g)
    kataku.write('\n')
    kataku.write(c + b + h)
    kataku.write('\n')
    kataku.write(c + b + i)
    kataku.write('\n')
    kataku.write(c + b + j)
    kataku.write('\n')
    kataku.write(c + d + a)
    kataku.write('\n')
    kataku.write(c + d + b)
    kataku.write('\n')
    kataku.write(c + d + e)
    kataku.write('\n')
    kataku.write(c + d + f)
    kataku.write('\n')
    kataku.write(c + d + g)
    kataku.write('\n')
    kataku.write(c + d + h)
    kataku.write('\n')
    kataku.write(c + d + i)
    kataku.write('\n')
    kataku.write(c + d + j)
    kataku.write('\n')
    kataku.write(c + e + a)
    kataku.write('\n')
    kataku.write(c + e + b)
    kataku.write('\n')
    kataku.write(c + e + d)
    kataku.write('\n')
    kataku.write(c + e + f)
    kataku.write('\n')
    kataku.write(c + e + g)
    kataku.write('\n')
    kataku.write(c + e + h)
    kataku.write('\n')
    kataku.write(c + e + i)
    kataku.write('\n')
    kataku.write(c + e + j)
    kataku.write('\n')
    kataku.write(d + a + b)
    kataku.write('\n')
    kataku.write(d + a + c)
    kataku.write('\n')
    kataku.write(d + a + e)
    kataku.write('\n')
    kataku.write(d + a + f)
    kataku.write('\n')
    kataku.write(d + a + g)
    kataku.write('\n')
    kataku.write(d + a + h)
    kataku.write('\n')
    kataku.write(d + a + i)
    kataku.write('\n')
    kataku.write(d + a + j)
    kataku.write('\n')
    kataku.write(d + b + a)
    kataku.write('\n')
    kataku.write(d + b + c)
    kataku.write('\n')
    kataku.write(d + b + e)
    kataku.write('\n')
    kataku.write(d + b + f)
    kataku.write('\n')
    kataku.write(d + b + g)
    kataku.write('\n')
    kataku.write(d + b + h)
    kataku.write('\n')
    kataku.write(d + b + i)
    kataku.write('\n')
    kataku.write(d + b + j)
    kataku.write('\n')
    kataku.write(d + c + a)
    kataku.write('\n')
    kataku.write(d + c + b)
    kataku.write('\n')
    kataku.write(d + c + e)
    kataku.write('\n')
    kataku.write(d + c + f)
    kataku.write('\n')
    kataku.write(d + c + g)
    kataku.write('\n')
    kataku.write(d + c + h)
    kataku.write('\n')
    kataku.write(d + c + i)
    kataku.write('\n')
    kataku.write(d + c + j)
    kataku.write('\n')
    kataku.write(d + e + a)
    kataku.write('\n')
    kataku.write(d + e + b)
    kataku.write('\n')
    kataku.write(d + e + c)
    kataku.write('\n')
    kataku.write(d + e + f)
    kataku.write('\n')
    kataku.write(d + e + g)
    kataku.write('\n')
    kataku.write(d + e + h)
    kataku.write('\n')
    kataku.write(d + e + i)
    kataku.write('\n')
    kataku.write(d + e + j)
    kataku.write('\n')
    kataku.write(d + f + a)
    kataku.write('\n')
    kataku.write(d + f + b)
    kataku.write('\n')
    kataku.write(d + f + c)
    kataku.write('\n')
    kataku.write(d + f + e)
    kataku.write('\n')
    kataku.write(d + f + g)
    kataku.write('\n')
    kataku.write(d + f + h)
    kataku.write('\n')
    kataku.write(d + f + i)
    kataku.write('\n')
    kataku.write(d + f + j)
    kataku.write('\n')
    kataku.write(d + g + a)
    kataku.write('\n')
    kataku.write(d + g + b)
    kataku.write('\n')
    kataku.write(d + g + c)
    kataku.write('\n')
    kataku.write(d + g + e)
    kataku.write('\n')
    kataku.write(d + g + f)
    kataku.write('\n')
    kataku.write(d + g + h)
    kataku.write('\n')
    kataku.write(d + g + i)
    kataku.write('\n')
    kataku.write(d + g + j)
    kataku.write('\n')
    kataku.write(d + h + a)
    kataku.write('\n')
    kataku.write(d + h + b)
    kataku.write('\n')
    kataku.write(d + h + c)
    kataku.write('\n')
    kataku.write(d + h + e)
    kataku.write('\n')
    kataku.write(d + h + f)
    kataku.write('\n')
    kataku.write(d + h + g)
    kataku.write('\n')
    kataku.write(d + h + i)
    kataku.write('\n')
    kataku.write(d + h + j)
    kataku.write('\n')
    kataku.write(d + i + a)
    kataku.write('\n')
    kataku.write(d + i + b)
    kataku.write('\n')
    kataku.write(d + i + c)
    kataku.write('\n')
    kataku.write(d + i + e)
    kataku.write('\n')
    kataku.write(d + i + f)
    kataku.write('\n')
    kataku.write(d + i + g)
    kataku.write('\n')
    kataku.write(d + i + h)
    kataku.write('\n')
    kataku.write(d + i + j)
    kataku.write('\n')
    kataku.write(d + j + a)
    kataku.write('\n')
    kataku.write(d + j + b)
    kataku.write('\n')
    kataku.write(d + j + c)
    kataku.write('\n')
    kataku.write(d + j + e)
    kataku.write('\n')
    kataku.write(d + j + f)
    kataku.write('\n')
    kataku.write(d + j + g)
    kataku.write('\n')
    kataku.write(d + j + h)
    kataku.write('\n')
    kataku.write(d + j + i)
    kataku.write('\n')
    kataku.write(e + a + b)
    kataku.write('\n')
    kataku.write(e + a + c)
    kataku.write('\n')
    kataku.write(e + a + d)
    kataku.write('\n')
    kataku.write(e + a + f)
    kataku.write('\n')
    kataku.write(e + a + g)
    kataku.write('\n')
    kataku.write(e + a + h)
    kataku.write('\n')
    kataku.write(e + a + i)
    kataku.write('\n')
    kataku.write(e + a + j)
    kataku.write('\n')
    kataku.write(e + b + a)
    kataku.write('\n')
    kataku.write(e + b + c)
    kataku.write('\n')
    kataku.write(e + b + d)
    kataku.write('\n')
    kataku.write(e + b + f)
    kataku.write('\n')
    kataku.write(e + b + g)
    kataku.write('\n')
    kataku.write(e + b + h)
    kataku.write('\n')
    kataku.write(e + b + i)
    kataku.write('\n')
    kataku.write(e + b + j)
    kataku.write('\n')
    kataku.write(e + c + a)
    kataku.write('\n')
    kataku.write(e + c + b)
    kataku.write('\n')
    kataku.write(e + c + d)
    kataku.write('\n')
    kataku.write(e + c + f)
    kataku.write('\n')
    kataku.write(e + c + g)
    kataku.write('\n')
    kataku.write(e + c + h)
    kataku.write('\n')
    kataku.write(e + c + i)
    kataku.write('\n')
    kataku.write(e + d + a)
    kataku.write('\n')
    kataku.write(e + d + b)
    kataku.write('\n')
    kataku.write(e + d + c)
    kataku.write('\n')
    kataku.write(e + d + f)
    kataku.write('\n')
    kataku.write(e + d + g)
    kataku.write('\n')
    kataku.write(e + d + h)
    kataku.write('\n')
    kataku.write(e + d + i)
    kataku.write('\n')
    kataku.write(e + d + j)
    kataku.write('\n')
    kataku.write(f + a + b)
    kataku.write('\n')
    kataku.write(f + a + c)
    kataku.write('\n')
    kataku.write(f + a + d)
    kataku.write('\n')
    kataku.write(f + a + e)
    kataku.write('\n')
    kataku.write(f + a + g)
    kataku.write('\n')
    kataku.write(f + a + h)
    kataku.write('\n')
    kataku.write(f + a + i)
    kataku.write('\n')
    kataku.write(f + a + j)
    kataku.write('\n')
    kataku.write(f + b + a)
    kataku.write('\n')
    kataku.write(f + b + c)
    kataku.write('\n')
    kataku.write(f + b + d)
    kataku.write('\n')
    kataku.write(f + b + e)
    kataku.write('\n')
    kataku.write(f + b + g)
    kataku.write('\n')
    kataku.write(f + b + h)
    kataku.write('\n')
    kataku.write(f + b + i)
    kataku.write('\n')
    kataku.write(f + b + j)
    kataku.write('\n')
    kataku.write(f + c + a)
    kataku.write('\n')
    kataku.write(f + c + b)
    kataku.write('\n')
    kataku.write(f + c + d)
    kataku.write('\n')
    kataku.write(f + c + e)
    kataku.write('\n')
    kataku.write(f + c + g)
    kataku.write('\n')
    kataku.write(f + c + h)
    kataku.write('\n')
    kataku.write(f + c + i)
    kataku.write('\n')
    kataku.write(f + c + j)
    kataku.write('\n')
    kataku.write(f + d + a)
    kataku.write('\n')
    kataku.write(f + d + b)
    kataku.write('\n')
    kataku.write(f + d + c)
    kataku.write('\n')
    kataku.write(f + d + e)
    kataku.write('\n')
    kataku.write(f + d + g)
    kataku.write('\n')
    kataku.write(f + d + h)
    kataku.write('\n')
    kataku.write(f + d + i)
    kataku.write('\n')
    kataku.write(f + d + j)
    kataku.write('\n')
    kataku.write(g + a + b)
    kataku.write('\n')
    kataku.write(g + a + c)
    kataku.write('\n')
    kataku.write(g + a + d)
    kataku.write('\n')
    kataku.write(g + a + e)
    kataku.write('\n')
    kataku.write(g + a + f)
    kataku.write('\n')
    kataku.write(g + a + h)
    kataku.write('\n')
    kataku.write(g + a + i)
    kataku.write('\n')
    kataku.write(g + a + j)
    kataku.write('\n')
    kataku.write(g + b + a)
    kataku.write('\n')
    kataku.write(g + b + c)
    kataku.write('\n')
    kataku.write(g + b + d)
    kataku.write('\n')
    kataku.write(g + b + e)
    kataku.write('\n')
    kataku.write(g + b + f)
    kataku.write('\n')
    kataku.write(g + b + h)
    kataku.write('\n')
    kataku.write(g + b + i)
    kataku.write('\n')
    kataku.write(g + b + j)
    kataku.write('\n')
    kataku.write(g + c + a)
    kataku.write('\n')
    kataku.write(g + c + b)
    kataku.write('\n')
    kataku.write(g + c + d)
    kataku.write('\n')
    kataku.write(g + c + e)
    kataku.write('\n')
    kataku.write(g + c + f)
    kataku.write('\n')
    kataku.write(g + c + h)
    kataku.write('\n')
    kataku.write(g + c + i)
    kataku.write('\n')
    kataku.write(g + c + j)
    kataku.write('\n')
    kataku.write(g + d + a)
    kataku.write('\n')
    kataku.write(g + d + b)
    kataku.write('\n')
    kataku.write(g + d + c)
    kataku.write('\n')
    kataku.write(g + d + e)
    kataku.write('\n')
    kataku.write(g + d + f)
    kataku.write('\n')
    kataku.write(g + d + h)
    kataku.write('\n')
    kataku.write(g + d + i)
    kataku.write('\n')
    kataku.write(g + d + j)
    kataku.write('\n')
    kataku.write(g + e + a)
    kataku.write('\n')
    kataku.write(g + e + b)
    kataku.write('\n')
    kataku.write(g + e + c)
    kataku.write('\n')
    kataku.write(g + e + d)
    kataku.write('\n')
    kataku.write(g + e + f)
    kataku.write('\n')
    kataku.write(g + e + h)
    kataku.write('\n')
    kataku.write(g + e + i)
    kataku.write('\n')
    kataku.write(g + e + j)
    kataku.write('\n')
    kataku.write(g + f + a)
    kataku.write('\n')
    kataku.write(g + f + b)
    kataku.write('\n')
    kataku.write(g + f + c)
    kataku.write('\n')
    kataku.write(g + f + d)
    kataku.write('\n')
    kataku.write(g + f + e)
    kataku.write('\n')
    kataku.write(g + f + h)
    kataku.write('\n')
    kataku.write(g + f + i)
    kataku.write('\n')
    kataku.write(g + f + j)
    kataku.write('\n')
    kataku.write(g + e + a)
    kataku.write('\n')
    kataku.write(g + e + b)
    kataku.write('\n')
    kataku.write(g + e + c)
    kataku.write('\n')
    kataku.write(g + e + d)
    kataku.write('\n')
    kataku.write(g + e + f)
    kataku.write('\n')
    kataku.write(g + e + h)
    kataku.write('\n')
    kataku.write(g + e + i)
    kataku.write('\n')
    kataku.write(g + e + j)
    kataku.write('\n')
    kataku.write(g + h + a)
    kataku.write('\n')
    kataku.write(g + h + b)
    kataku.write('\n')
    kataku.write(g + h + c)
    kataku.write('\n')
    kataku.write(g + h + d)
    kataku.write('\n')
    kataku.write(g + h + f)
    kataku.write('\n')
    kataku.write(g + h + e)
    kataku.write('\n')
    kataku.write(g + h + i)
    kataku.write('\n')
    kataku.write(g + h + j)
    kataku.write('\n')
    kataku.write(g + i + a)
    kataku.write('\n')
    kataku.write(g + i + b)
    kataku.write('\n')
    kataku.write(g + i + c)
    kataku.write('\n')
    kataku.write(g + i + d)
    kataku.write('\n')
    kataku.write(g + i + f)
    kataku.write('\n')
    kataku.write(g + i + e)
    kataku.write('\n')
    kataku.write(g + i + h)
    kataku.write('\n')
    kataku.write(g + i + j)
    kataku.write('\n')
    kataku.write(g + j + a)
    kataku.write('\n')
    kataku.write(g + j + b)
    kataku.write('\n')
    kataku.write(g + j + c)
    kataku.write('\n')
    kataku.write(g + j + d)
    kataku.write('\n')
    kataku.write(g + j + f)
    kataku.write('\n')
    kataku.write(g + j + e)
    kataku.write('\n')
    kataku.write(g + j + h)
    kataku.write('\n')
    kataku.write(g + j + i)
    kataku.write('\n')
    kataku.write(h + a + b)
    kataku.write('\n')
    kataku.write(h + a + c)
    kataku.write('\n')
    kataku.write(h + a + d)
    kataku.write('\n')
    kataku.write(h + a + e)
    kataku.write('\n')
    kataku.write(h + a + f)
    kataku.write('\n')
    kataku.write(h + a + g)
    kataku.write('\n')
    kataku.write(h + a + i)
    kataku.write('\n')
    kataku.write(h + a + j)
    kataku.write('\n')
    kataku.write(h + b + a)
    kataku.write('\n')
    kataku.write(h + b + c)
    kataku.write('\n')
    kataku.write(h + b + d)
    kataku.write('\n')
    kataku.write(h + b + e)
    kataku.write('\n')
    kataku.write(h + b + f)
    kataku.write('\n')
    kataku.write(h + b + g)
    kataku.write('\n')
    kataku.write(h + b + i)
    kataku.write('\n')
    kataku.write(h + b + j)
    kataku.write('\n')
    kataku.write(h + c + a)
    kataku.write('\n')
    kataku.write(h + c + b)
    kataku.write('\n')
    kataku.write(h + c + d)
    kataku.write('\n')
    kataku.write(h + c + e)
    kataku.write('\n')
    kataku.write(h + c + f)
    kataku.write('\n')
    kataku.write(h + c + g)
    kataku.write('\n')
    kataku.write(h + c + i)
    kataku.write('\n')
    kataku.write(h + c + j)
    kataku.write('\n')
    kataku.write(h + d + a)
    kataku.write('\n')
    kataku.write(h + d + b)
    kataku.write('\n')
    kataku.write(h + d + c)
    kataku.write('\n')
    kataku.write(h + d + e)
    kataku.write('\n')
    kataku.write(h + d + f)
    kataku.write('\n')
    kataku.write(h + d + g)
    kataku.write('\n')
    kataku.write(h + d + i)
    kataku.write('\n')
    kataku.write(h + d + j)
    kataku.write('\n')
    kataku.write(h + e + a)
    kataku.write('\n')
    kataku.write(h + e + b)
    kataku.write('\n')
    kataku.write(h + e + c)
    kataku.write('\n')
    kataku.write(h + e + d)
    kataku.write('\n')
    kataku.write(h + e + f)
    kataku.write('\n')
    kataku.write(h + e + g)
    kataku.write('\n')
    kataku.write(h + e + i)
    kataku.write('\n')
    kataku.write(h + e + j)
    kataku.write('\n')
    kataku.write(h + f + a)
    kataku.write('\n')
    kataku.write(h + f + b)
    kataku.write('\n')
    kataku.write(h + f + c)
    kataku.write('\n')
    kataku.write(h + f + d)
    kataku.write('\n')
    kataku.write(h + f + e)
    kataku.write('\n')
    kataku.write(h + f + g)
    kataku.write('\n')
    kataku.write(h + f + i)
    kataku.write('\n')
    kataku.write(h + f + j)
    kataku.write('\n')
    kataku.write(h + g + a)
    kataku.write('\n')
    kataku.write(h + g + b)
    kataku.write('\n')
    kataku.write(h + g + c)
    kataku.write('\n')
    kataku.write(h + g + d)
    kataku.write('\n')
    kataku.write(h + g + e)
    kataku.write('\n')
    kataku.write(h + g + f)
    kataku.write('\n')
    kataku.write(h + g + i)
    kataku.write('\n')
    kataku.write(h + g + j) 
    kataku.write('\n')
    kataku.write(h + i + a)
    kataku.write('\n')
    kataku.write(h + i + b)
    kataku.write('\n')
    kataku.write(h + i + c)
    kataku.write('\n')
    kataku.write(h + i + d)
    kataku.write('\n')
    kataku.write(h + i + e)
    kataku.write('\n')
    kataku.write(h + i + f)
    kataku.write('\n')
    kataku.write(h + i + g)
    kataku.write('\n')
    kataku.write(h + i + j)
    kataku.write('\n')
    kataku.write(h + j + a)
    kataku.write('\n')
    kataku.write(h + j + b)
    kataku.write('\n')
    kataku.write(h + j + c)
    kataku.write('\n')
    kataku.write(h + j + d)
    kataku.write('\n')
    kataku.write(h + j + e)
    kataku.write('\n')
    kataku.write(h + j + f)
    kataku.write('\n')
    kataku.write(h + j + g)
    kataku.write('\n')
    kataku.write(h + j + i)
    kataku.write('\n')
    kataku.write(i + a + c)
    kataku.write('\n')
    kataku.write(i + a + d)
    kataku.write('\n')
    kataku.write(i + a + e)
    kataku.write('\n')
    kataku.write(i + a + f)
    kataku.write('\n')
    kataku.write(i + a + g)
    kataku.write('\n')
    kataku.write(i + a + h)
    kataku.write('\n')
    kataku.write(i + a + j)
    kataku.write('\n')
    kataku.write(i + b + a)
    kataku.write('\n')
    kataku.write(i + b + c)
    kataku.write('\n')
    kataku.write(i + b + d)
    kataku.write('\n')
    kataku.write(i + b + e)
    kataku.write('\n')
    kataku.write(i + b + f)
    kataku.write('\n')
    kataku.write(i + b + g)
    kataku.write('\n')
    kataku.write(i + b + h)
    kataku.write('\n')
    kataku.write(i + b + j)
    kataku.write('\n')
    kataku.write(i + c + a)
    kataku.write('\n')
    kataku.write(i + c + b)
    kataku.write('\n')
    kataku.write(i + c + d)
    kataku.write('\n')
    kataku.write(i + c + e)
    kataku.write('\n')
    kataku.write(i + c + f)
    kataku.write('\n')
    kataku.write(i + c + g)
    kataku.write('\n')
    kataku.write(i + c + h)
    kataku.write('\n')
    kataku.write(i + c + j)
    kataku.write('\n')
    kataku.write(i + d + a)
    kataku.write('\n')
    kataku.write(i + d + b)
    kataku.write('\n')
    kataku.write(i + d + c)
    kataku.write('\n')
    kataku.write(i + d + e)
    kataku.write('\n')
    kataku.write(i + d + f)
    kataku.write('\n')
    kataku.write(i + d + g)
    kataku.write('\n')
    kataku.write(i + d + h)
    kataku.write('\n')
    kataku.write(i + d + j)
    kataku.write('\n')
    kataku.write(i + e + a)
    kataku.write('\n')
    kataku.write(i + e + b)
    kataku.write('\n')
    kataku.write(i + e + c)
    kataku.write('\n')
    kataku.write(i + e + d)
    kataku.write('\n')
    kataku.write(i + e + f)
    kataku.write('\n')
    kataku.write(i + e + g)
    kataku.write('\n')
    kataku.write(i + e + h)
    kataku.write('\n')
    kataku.write(i + e + j)
    kataku.write('\n')
    kataku.write(i + f + a)
    kataku.write('\n')
    kataku.write(i + f + b)
    kataku.write('\n')
    kataku.write(i + f + c)
    kataku.write('\n')
    kataku.write(i + f + d)
    kataku.write('\n')
    kataku.write(i + f + e)
    kataku.write('\n')
    kataku.write(i + f + g)
    kataku.write('\n')
    kataku.write(i + f + h)
    kataku.write('\n')
    kataku.write(i + f + j)
    kataku.write('\n')
    kataku.write(i + g + a)
    kataku.write('\n')
    kataku.write(i + g + b)
    kataku.write('\n')
    kataku.write(i + g + c)
    kataku.write('\n')
    kataku.write(i + g + d)
    kataku.write('\n')
    kataku.write(i + g + e)
    kataku.write('\n')
    kataku.write(i + g + f)
    kataku.write('\n')
    kataku.write(i + g + h)
    kataku.write('\n')
    kataku.write(i + g + j) 
    kataku.write('\n')
    kataku.write(i + h + a)
    kataku.write('\n')
    kataku.write(i + h + b)
    kataku.write('\n')
    kataku.write(i + h + c)
    kataku.write('\n')
    kataku.write(i + h + d)
    kataku.write('\n')
    kataku.write(i + h + e)
    kataku.write('\n')
    kataku.write(i + h + f)
    kataku.write('\n')
    kataku.write(i + h + g)
    kataku.write('\n')
    kataku.write(i + h + j)
    kataku.write('\n')
    kataku.write(i + j + a)
    kataku.write('\n')
    kataku.write(i + j + b)
    kataku.write('\n')
    kataku.write(i + j + c)
    kataku.write('\n')
    kataku.write(i + j + d)
    kataku.write('\n')
    kataku.write(i + j + e)
    kataku.write('\n')
    kataku.write(i + j + f)
    kataku.write('\n')
    kataku.write(i + j + g)
    kataku.write('\n')
    kataku.write(i + j + h)
    kataku.write('\n')
    kataku.write(j + a + c)
    kataku.write('\n')
    kataku.write(j + a + d)
    kataku.write('\n')
    kataku.write(j + a + e)
    kataku.write('\n')
    kataku.write(j + a + f)
    kataku.write('\n')
    kataku.write(j + a + g)
    kataku.write('\n')
    kataku.write(j + a + h)
    kataku.write('\n')
    kataku.write(j + a + i)
    kataku.write('\n')
    kataku.write(j + b + a)
    kataku.write('\n')
    kataku.write(j + b + c)
    kataku.write('\n')
    kataku.write(j + b + d)
    kataku.write('\n')
    kataku.write(j + b + e)
    kataku.write('\n')
    kataku.write(j + b + f)
    kataku.write('\n')
    kataku.write(j + b + g)
    kataku.write('\n')
    kataku.write(j + b + h)
    kataku.write('\n')
    kataku.write(j + b + i)
    kataku.write('\n')
    kataku.write(j + c + a)
    kataku.write('\n')
    kataku.write(j + c + b)
    kataku.write('\n')
    kataku.write(j + c + d)
    kataku.write('\n')
    kataku.write(j + c + e)
    kataku.write('\n')
    kataku.write(j + c + f)
    kataku.write('\n')
    kataku.write(j + c + g)
    kataku.write('\n')
    kataku.write(j + c + h)
    kataku.write('\n')
    kataku.write(j + c + i)
    kataku.write('\n')
    kataku.write(j + d + a)
    kataku.write('\n')
    kataku.write(j + d + b)
    kataku.write('\n')
    kataku.write(j + d + c)
    kataku.write('\n')
    kataku.write(j + d + e)
    kataku.write('\n')
    kataku.write(j + d + f)
    kataku.write('\n')
    kataku.write(j + d + g)
    kataku.write('\n')
    kataku.write(j + d + h)
    kataku.write('\n')
    kataku.write(j + d + i)
    kataku.write('\n')
    kataku.write(j + e + a)
    kataku.write('\n')
    kataku.write(j + e + b)
    kataku.write('\n')
    kataku.write(j + e + c)
    kataku.write('\n')
    kataku.write(j + e + d)
    kataku.write('\n')
    kataku.write(j + e + f)
    kataku.write('\n')
    kataku.write(j + e + g)
    kataku.write('\n')
    kataku.write(j + e + h)
    kataku.write('\n')
    kataku.write(j + e + i)
    kataku.write('\n')
    kataku.write(j + f + a)
    kataku.write('\n')
    kataku.write(j + f + b)
    kataku.write('\n')
    kataku.write(j + f + c)
    kataku.write('\n')
    kataku.write(j + f + d)
    kataku.write('\n')
    kataku.write(j + f + e)
    kataku.write('\n')
    kataku.write(j + f + g)
    kataku.write('\n')
    kataku.write(j + f + h)
    kataku.write('\n')
    kataku.write(j + f + i)
    kataku.write('\n')
    kataku.write(j + g + a)
    kataku.write('\n')
    kataku.write(j + g + b)
    kataku.write('\n')
    kataku.write(j + g + c)
    kataku.write('\n')
    kataku.write(j + g + d)
    kataku.write('\n')
    kataku.write(j + g + e)
    kataku.write('\n')
    kataku.write(j + g + f)
    kataku.write('\n')
    kataku.write(j + g + h)
    kataku.write('\n')
    kataku.write(j + g + i) 
    kataku.write('\n')
    kataku.write(j + h + a)
    kataku.write('\n')
    kataku.write(j + h + b)
    kataku.write('\n')
    kataku.write(j + h + c)
    kataku.write('\n')
    kataku.write(j + h + d)
    kataku.write('\n')
    kataku.write(j + h + e)
    kataku.write('\n')
    kataku.write(j + h + f)
    kataku.write('\n')
    kataku.write(j + h + g)
    kataku.write('\n')
    kataku.write(j + h + i)
    kataku.write('\n')
    kataku.write(j + i + a)
    kataku.write('\n')
    kataku.write(j + i + b)
    kataku.write('\n')
    kataku.write(j + i + c)
    kataku.write('\n')
    kataku.write(j + i + d)
    kataku.write('\n')
    kataku.write(j + i + e)
    kataku.write('\n')
    kataku.write(j + i + f)
    kataku.write('\n')
    kataku.write(j + i + g)
    kataku.write('\n')
    kataku.write(j + i + h)
    print '''
\033[1;25m     _  _  _  _       _  _  _  _    _           _  _  _  _  _     
    (_)(_)(_)(_)    _(_)(_)(_)(_)_ (_) _       (_)(_)(_)(_)(_) 
    (_)       (_)_ (_)          (_)(_)(_)_     (_)(_)               
    (_)         (_)(_)          (_)(_)  (_)_   (_)(_) _  _          
    (_)         (_)(_)          (_)(_)    (_)_ (_)(_)(_)(_)         
    (_)        _(_)(_)          (_)(_)      (_)(_)(_)               
    (_) _  _  (_)  (_)_  _  _  _(_)(_)         (_)(_) _  _  _     
    (_)(_)(_)(_)     (_)(_)(_)(_)  (_)         (_)(_)(_)(_)(_)\033[1;m
\033[1;91m    ____________________________________________________________ \033[1;m  
\033[1;36m    File disimpan sebagai : ''' + nama 
except KeyboardInterrupt:
    print '''\033[1;m \033[1;36
  _        ____                                      
 /_|   _/_  /  _ /_ /  /|/| _ _  / __/_ // _       _ 
(  |/)(/(/ (  (-((//) /   |(-//)()(//(/(/((//)/)(/(/ 
                                                /  
\033[1;m    '''
